[srv_db]
srv-db21 ansible_host=213.165.212.20 ansible_user=user01
srv-db22 ansible_host=158.160.69.64 ansible_user=user01
srv-db23 ansible_host=213.165.216.246 ansible_user=user01

[srv_adm]
srv_adm01 ansible_host=13.165.218.188 ansible_ssh_private_key_file=/home/tserg/.ssh/id_rsa

[srv_haproxy]
srv_haproxy01 ansible_host=213.165.209.48 ansible_user=user01

