# Пример файла, лежащего в другом месте
# Используется, чтобы не было паролей в конфигах
# /etc/patroni/secrets.env
POSTGRES_SUPER_PASSWORD: "secure_super_Password_123"
POSTGRES_REPLICATION_PASSWORD: "repl_Password_456"
POSTGRES_ADMIN_PASSWORD: "admin_Password!789"